# Generated by Django 2.2.10 on 2020-04-16 18:07

from django.db import migrations, models
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps

def update_invite_required(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Realm = apps.get_model('zerver', 'Realm')
    RealmDomain = apps.get_model('zerver', 'RealmDomain')
    for realm in Realm.objects.all():
        default_invite_required = realm.default_invite_required
        for realm_domain in RealmDomain.objects.filter(realm=realm):
            realm_domain.invite_required = default_invite_required
            realm_domain.save(update_fields=['invite_required'])


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0276_rename_invite_required_to_default_invite_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmdomain',
            name='invite_required',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_invite_required, migrations.RunPython.noop)
    ]
